### ISSUE TITLE
Webpack chunk size

### ISSUE THREAD

**Issue by SIKaran** [jwald1/stimulus-validation#1]
I am using this library with webpack and typescript.. My chunk size gets 330kb by using webpack bundle analyzer i found that stimulus_validation.min.js bundles stimulus along

Another issue i found is library is build with development mode set in webpack

**Comment by jwald1** [comment]
You are correct @SIKaran. I'm planning to rewrite this package from scratch to make this library more useful. In the new version, this issue will be solved.

**Comment by SIKaran** [comment]
Till then can we got fix the chunk size issue,.. Have you made any progress with rewriting

**Comment by jwald1** [comment]
@SIKaran, I've rebuilt the package using Rollbar. Here is the output from Rollbar
```
Destination: dist/validation-controller.js   │
│   Bundle Size:  14.6 KB                        │
│   Minified Size:  8.44 KB                      │
│   Gzipped Size:  2.42 KB     
```

**Comment by SIKaran** [comment]
@jwald1 Thats a great improvement, never heard Rollbar can give me the link of its website.

**Comment by jwald1** [comment]
My mistake, it's Rollup, not Rollbar. Here is the link [Rollup](https://rollupjs.org/guide/en)
