### ISSUE TITLE
Programmatically add validation rules

### ISSUE THREAD

**Issue by tbuyle** [jwald1/stimulus-validation#3]
I'd like to be able to automatically add validation rules for some fields. 

For example, I'd like to be able yo automatically add an "email" rules for all HTML5 input with email type.

Is this possible to add rules to an element without using static rules declaration ?

**Comment by jwald1** [comment]
I'm currently building a Stimulus controller that will auto validate HTML5 rules, but with this controller, it's not possible.

**Comment by tbuyle** [comment]
Ok.

In the meanwhile, I also found this Tutorial https://www.jorgemanrubia.com/2019/02/16/form-validations-with-html5-and-modern-rails/ with a nice HTML5 validation controller ;-D
